name: NuGet

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual tag'
  push: 
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Set Node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12.x
      - run: cd src/tinyproxy_dashboard && npm install && npm run build
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION} src/TinyProxy.csproj
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build src/TinyProxy.csproj
      - name: Pack
        run: cp README.md src/ && dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output . src/TinyProxy.csproj
      - name: Push
        run: nuget push **\*.nupkg -NoSymbols -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
